### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by domenic** [domfarolino/specfmt#14]
Steps to reproduce:

1. Clone https://github.com/whatwg/html/pull/8712/files
2. `cargo install specfmt`
3. `specfmt`

Result: no change, despite many newly-introduced lines that are over the limit.

**Comment by domenic** [comment]
It works better if built from source, presumably due to https://github.com/domfarolino/specfmt/commit/bafad8d4ecd043d05fc1974d375eca2d65405461 . However it produces diffs like 

```html
  <p>The <dfn for="iframe" element-attr><code data-x="attr-iframe-srcdoc">srcdoc</code></dfn>
  attribute gives the content of the page that the element's <span data-x="nav-container-navigable">navigable</span> is
  to contain. The value of the attribute is the source of <dfn export>an <code>iframe</code> <code
  data-x="attr-iframe-srcdoc">srcdoc</code> document</dfn>.</p>
```

->

```
  <p>The <dfn for="iframe" element-attr><code data-x="attr-iframe-srcdoc">srcdoc</code></dfn>
  attribute gives the content of the page that the element's <span
  data-x="nav-container-navigable">navigable</span> is
  to contain. The value of the attribute is the source of <dfn export>an <code>iframe</code> <code
  data-x="attr-iframe-srcdoc">srcdoc</code> document</dfn>.</p>
```

because it's not touching the entire paragraph, just the changed line. So I need to do the work manually anyway :(

**Comment by domfarolino** [comment]
Yeah, looks like I forgot to publish `specfmt` after fixing it for HTML. I just did that, so `cargo install specfmt` should give you the most updated version and should work (might need to `rustup update` though given the clap dependency that seems to rely on rust v1.64).

> However it produces diffs like [...] because it's not touching the entire paragraph, just the changed line. So I need to do the work manually anyway :(

That's https://github.com/domfarolino/specfmt/issues/8, right?

**Comment by domenic** [comment]
Yep, that's #8! Looks like we can close this.
